### ISSUE TITLE
Mention common pitfalls

### ISSUE THREAD

**Issue by mirdaki** [OpenTechStrategies/open-source-archetypes#8]
I would really love to see information about common ways projects fail (for instance, maybe sticking with the Rocket Ship to Mars approach for too long often leads to burn out). It would be useful information for projects to consider before they decide on a strategy.

**Comment by kfogel** [comment]
Yes... hmmm.  I mean, this would be useful, but on the other hand, we should be cautious about turning an archetypes guide into a full-blown "how to manage an open source project" guide. Not sure how to strike this balance yet; just noting here that it's an issue.

**Comment by erlend-sh** [comment]
I can agree that "how to manage an open source project" is far out of scope and is already well documented elsewhere, but "how to execute an open source business model" is very closely in line with what the archetypes guide is trying to provide already. Cohesive documentation about this subject is also woefully lacking in the public domain.

**Comment by mirdaki** [comment]
Good point about keeping the focus of the guide. Maybe creating another document to compliment this one would help? That way this one could keep it's scope and still stand on its own.

**Comment by kfogel** [comment]
I think the new section "Business Models and Archetypes" addresses this as much as we can address it in this document.  @mirdaki I agree there's a need for what you describe, even if we aren't going to meet that need here.  (I don't know if any of the material at [Producing Open Source Software](https://producingoss.com/) addresses some of it -- let us know.)
